# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Ajax
version:      0.01
version_from: Ajax.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
